### ISSUE TITLE
price: rounding error when formatting specific negative price

### ISSUE THREAD

**Issue by ChristopherSchwab** [i-love-flamingo/flamingo-commerce#336]
We noticed a rounding error for a specific negative price value when formatting that price.
I added a failing regression test to https://github.com/i-love-flamingo/flamingo-commerce/tree/rounding-error-format-negative-price ( https://github.com/i-love-flamingo/flamingo-commerce/commit/2a99c4f341951ae42da4bee92cccbb82650bcc67 ) to illustrate the issue with this failing assertion:

```
price := priceDomain.NewFromFloat(-161.92, "USD")
formatted := service.FormatPrice(price)
// -161.92 expected, but getting -161.91
assert.Equal(t, "-USD161.92", formatted)
```

Other (negative) values work fine, only know of this one specific value at the moment.

**Comment by carstendietrich** [comment]
fixed in release v3.5.0
