### ISSUE TITLE
How to handle phone number?

### ISSUE THREAD

**Issue by mishop** [i-love-flamingo/flamingo-commerce#496]
I tried telephoneNumber, TelephoneNumber, Telephone but not handle 🤔
`        div.col-md-4.mb-2
          div.md-form
            +inputField("billingAddress","telephoneNumber","Telephone", billingForm,billingForm.data.telephoneNumber)
            +fieldError("telephoneNumber",billingForm)`

**Comment by carstendietrich** [comment]
See the Form struct for all available fields: https://github.com/i-love-flamingo/flamingo-commerce/blob/master/cart/interfaces/controller/forms/basics.go#L30

In your case, you are looking for `billingForm.data.phoneNumber`.

In addition, you can also use country and area code if needed: `billingForm.data.phoneAreaCode` / `billingForm.data.phoneCountryCode`

**Comment by tessig** [comment]
we consider this as answered. Feel free to raise further questions!
