### ISSUE TITLE
github.com/leekchan/accounting v1.0.0, there no such tag

### ISSUE THREAD

**Issue by idc77** [i-love-flamingo/flamingo-commerce#516]
Doing a `go mod tidy`
I get

```
go mod tidy
go: downloading github.com/leekchan/accounting v1.0.0
go: downloading github.com/hashicorp/golang-lru v0.6.0
go: code.icod.de/exp/cbdshop/cmd imports
	flamingo.me/flamingo-commerce/v3/product imports
	flamingo.me/flamingo-commerce/v3/price imports
	flamingo.me/flamingo-commerce/v3/price/interfaces/templatefunctions imports
	flamingo.me/flamingo-commerce/v3/price/application imports
	github.com/leekchan/accounting: reading github.com/leekchan/accounting/go.mod at revision v1.0.0: unknown revision v1.0.0
```

and true enough`github.com/leekchan/accounting` has no v1.0.0 tag.

But your go.mod file requires v1.0.0
https://github.com/i-love-flamingo/flamingo-commerce/blob/bacd0f1588d6116512708e1f6c4bfc1e81fb0786/go.mod#L20

https://github.com/leekchan/accounting/tags

**Comment by tessig** [comment]
thanks for pointing that out.
There once was a tag 1.0.0, go.dev still has it https://pkg.go.dev/github.com/leekchan/accounting?tab=versions

I think we go back then to the latest release.
