### ISSUE TITLE
Libs outdated

### ISSUE THREAD

**Issue by mishop** [i-love-flamingo/flamingo-commerce#556]
I found same bugs in latest version
Jaeger migrated to OpenTelemetry no update more
``` # contrib.go.opencensus.io/exporter/jaeger
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/agent.go:76:11: a.client.SeqId undefined (type *agent.AgentClient has no field or method SeqId)
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/agent.go:77:31: not enough arguments in call to a.client.EmitBatch
	have (*"github.com/uber/jaeger-client-go/thrift-gen/jaeger".Batch)
	want (context.Context, *"github.com/uber/jaeger-client-go/thrift-gen/jaeger".Batch)
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/jaeger.go:363:22: not enough arguments in call to obj.Write
	have (*thrift.TBinaryProtocol)
	want (context.Context, thrift.TProtocol)``` 

After remove jeager bug lines, I got this bug. 

``` # flamingo.me/flamingo-commerce-adapter-standalone/commercesearch/infrastructure/commercesearch
../pkg/mod/flamingo.me/flamingo-commerce-adapter-standalone@v0.0.4-beta/commercesearch/infrastructure/commercesearch/bleverepository.go:698:14: cannot use string(searchDomain.TreeFacet) (constant "TreeFacet" of type string) as "flamingo.me/flamingo-commerce/v3/search/domain".FacetType value in struct literal
../pkg/mod/flamingo.me/flamingo-commerce-adapter-standalone@v0.0.4-beta/commercesearch/infrastructure/commercesearch/bleverepository.go:713:14: cannot use string(searchDomain.ListFacet) (constant "ListFacet" of type string) as "flamingo.me/flamingo-commerce/v3/search/domain".FacetType value in struct literal```

**Comment by mishop** [comment]
`go version go1.22.1 darwin/amd64
misho@Mishos-MacBook-Pro:~/go/example-commerce% make serve  
DEBUG=1 CONTEXT=dev:testproducts go run main.go serve
# contrib.go.opencensus.io/exporter/jaeger
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/agent.go:76:11: a.client.SeqId undefined (type *agent.AgentClient has no field or method SeqId)
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/agent.go:77:31: not enough arguments in call to a.client.EmitBatch
	have (*"github.com/uber/jaeger-client-go/thrift-gen/jaeger".Batch)
	want (context.Context, *"github.com/uber/jaeger-client-go/thrift-gen/jaeger".Batch)
../pkg/mod/contrib.go.opencensus.io/exporter/jaeger@v0.2.1/jaeger.go:363:22: not enough arguments in call to obj.Write
	have (*thrift.TBinaryProtocol)
	want (context.Context, thrift.TProtocol)
# flamingo.me/flamingo-commerce-adapter-standalone/commercesearch/infrastructure/productsearch
../pkg/mod/flamingo.me/flamingo-commerce-adapter-standalone@v0.0.3-beta/commercesearch/infrastructure/productsearch/bleverepository.go:688:14: cannot use string(searchDomain.TreeFacet) (constant "TreeFacet" of type string) as "flamingo.me/flamingo-commerce/v3/search/domain".FacetType value in struct literal
../pkg/mod/flamingo.me/flamingo-commerce-adapter-standalone@v0.0.3-beta/commercesearch/infrastructure/productsearch/bleverepository.go:703:14: cannot use string(searchDomain.ListFacet) (constant "ListFacet" of type string) as "flamingo.me/flamingo-commerce/v3/search/domain".FacetType value in struct literal
make: *** [serve] Error 1
zsh: exit 2     make serve
`

**Comment by IvanMaidurov** [comment]
resolved in [this Issue](https://github.com/i-love-flamingo/flamingo-commerce-adapter-standalone/issues/17)
